# configs/forecast_evaluation.yaml
checkpoint_path:
  type: str
  required: true
  default: "C:/WUR/ssm_time_series/checkpoints/forecast_encoder_20251014_2306/best.pt"
  description: "Path to model checkpoint (required)"

data_dir:
  type: str
  default: "C:/WUR/ssm_time_series/ICML_datasets"
  description: "Dataset directory"

filename:
  type: str
  # default: "/ETT-small/ETTh1.csv"
  default: null
  description: "Optional filename inside data_dir"

dataset_name:
  type: str
  default: ""
  description: "Specific dataset name"

batch_size:
  type: int
  default: 12
  description: "Evaluation batch size"

val_batch_size:
  type: int
  default: 256
  description: "Validation batch size"

token_size:
  type: int
  default: 32
  description: "Token size used during training"

model_dim:
  type: int
  default: 768
  description: "Model dimension"

embedding_dim:
  type: int
  default: 128
  description: "Encoder embedding dimension"

depth:
  type: int
  default: 6
  description: "Number of Mamba blocks"

split:
  type: str
  default: "val"
  choices: ["train", "val", "test"]
  description: "Which split to evaluate"

output_dir:
  type: str
  default: "../checkpoints"
  description: "Directory to store evaluation artifacts"

num_workers:
  type: int
  default: 4
  description: "Number of data loading workers"