# configs/multi_dataset_evaluation.yaml
checkpoint_path:
  type: str
  required: true
  default: "C:/WUR/ssm_time_series/checkpoints/forecast_encoder_20251014_2306/best.pt"
  description: "Path to model checkpoint (required)"

base_data_dir:
  type: str
  default: "C:/WUR/ssm_time_series"
  description: "Base directory containing ICML_datasets folder"

batch_size:
  type: int
  default: 12
  description: "Evaluation batch size"

val_batch_size:
  type: int
  default: 256
  description: "Validation batch size"

token_size:
  type: int
  default: 32
  description: "Token size used during training"

model_dim:
  type: int
  default: 768
  description: "Model dimension"

embedding_dim:
  type: int
  default: 128
  description: "Encoder embedding dimension"

depth:
  type: int
  default: 6
  description: "Number of Mamba blocks"

split:
  type: str
  default: "test"
  choices: ["train", "val", "test"]
  description: "Which split to evaluate"

output_dir:
  type: str
  default: "C:/WUR/ssm_time_series/eval_runs"
  description: "Directory to store evaluation artifacts"

num_workers:
  type: int
  default: 4
  description: "Number of data loading workers"

model_name:
  type: str
  default: "MambaEncoder"
  description: "Name for the model in results table"